### ISSUE TITLE
请问下在SpringBoot中怎么结合norm使用？

### ISSUE THREAD

**Issue by fengjunren** [xcr1234/norm#1]
可以吗？麻烦了

**Comment by xcr1234** [comment]
完整的例子：[springboot-norm.zip](https://pan.baidu.com/s/1dzecfSIKVh1nD-tXEQQCMA)

**Comment by xcr1234** [comment]
已更新至版本1.7，修复了很多bug，欢迎使用 🐤

**Comment by junfengren** [comment]
谢谢
